### ISSUE TITLE
How to deploy to Netlify?

### ISSUE THREAD

**Issue by hibangun** [doug2k1/nanogen#12]
Any idea how to deploy to netlify, I got something like
```
Page Not found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.
```
Any Netlify settings that needs to follow?

**Comment by doug2k1** [comment]
There is a "Deploy to Netlify" button on the home page of this repository. You could use that button to deploy the sample site and then add your content. Or check the "netlify.toml" on the template repository: https://github.com/doug2k1/nanogen-template
