### ISSUE TITLE
Includes from pages

### ISSUE THREAD

**Issue by sn0n** [doug2k1/nanogen#4]
as currently setup, it seems includes do not currently work from pages folder? at least I haven't been able to figure out how to get a file included from a page.ejs file. is there an alternative I'm missing? haven't been able to track anything down.

**Comment by doug2k1** [comment]
Hi! Thanks for reporting! There was really an issue with the way EJS pages were rendered, that prevented them from using includes.

It should be fixed now.

If you have any problems, feel free to reopen.
