### ISSUE TITLE
customizing output paths

### ISSUE THREAD

**Issue by pkra** [doug2k1/nanogen#5]
First off, thanks for making this -- I find it very appealing.

Right now there's

https://github.com/doug2k1/nanogen/blob/17fec73c05ce86ae418753a2c3d50645557ae87f/lib/index.js#L88

I tend to prefer something like 

```
fse.writeFileSync(`${destPath}/${fileData.name}/index.html`, completePage);
```

I'm happy to just fork to keep things as concise as they are right now.  But I thought I'd ask what you think.

**Comment by doug2k1** [comment]
Hi! Good suggestion! It would simplify the site links.

I'll add to the features for the next release.

Thanks!

**Comment by doug2k1** [comment]
Done. The only extra verification I had to do is if the original file name is already `index`, it does not create `index/index.html`. ;-) 

If you encounter any problem, let me know.

**Comment by pkra** [comment]
Awesome. Thanks for making the change!
